<html>
    <head>
        <title>本日の運勢</title>
    </head>
    <body>
        <h1>本日の運勢</h1>
        <table border="0">
            <tr>
                <td>全体運：</td>
            </tr>
             <tr>
                <td></td>
            </tr>
            <tr>
                <td></td>
            </tr>
            <tr>
                <td>健康運：</td>
            </tr>
            <tr>
                <td>金運：</td>
            </tr>
            <tr>
                <td>恋愛運：</td>
            </tr>
        </table>
    </body>
</html>
